AWSTemplateFormatVersion: 2010-09-09

# These are inputs parameters for the template - give the flexibility to change some settings without having to modify the template code.
Parameters:
  EC2InstanceType:
    Type: String
  EC2AMI:
    #allows template to get the latest AMI without having to specify the exact version
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>' 
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

# Where resources that CloudFormation will manage are defined and configured
Resources:
  
  # The security groups function like a firewall for the EC2 instance.
  SecurityGroup
    Type: AWS::EC2::SecurityGroup
    Properties:
    # '!Sub' is a CloudFormation function that performs string interpolation.
      GroupDescription: !Sub 'Internal Security group for ${AWS::StackName}'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  # The IAM role is used to define the EC2 instance permissions.
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - "ec2.amazonaws.com"
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  # The instance profile tie our IAM role to the EC2 instance.
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - Ref: InstanceRole

  # Create the EC2 Instance itself
  Instance:
    Type: AWS::EC2::Instance
    CreationPolicy: 
      ResourceSignal:
        Timeout: PT15M
        Count: 1
    Metadata:
      AWS::CloudFormation::Init:
        config:
          packages: 
            yum:
              wget: []
              unzip: []
    Properties:
      ImageId: !Ref EC2AMI
      InstanceType: !Ref EC2InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      Monitoring: true
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId 
      UserData:
        # ... 
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

# Outputs are Like return values for the template - uses to make it easy to find some of the resources that CloudFormation will create
Outputs:
