name: aws-bootstrap

on: push

jobs:
  Test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.event.repository.name }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.event.repository.name }}-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lakesyde
          password: lakesyde03

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          outputs: type=docker
          tags: |
            ${{github.event.repository.name}}:stable-${{ github.sha }}
            ${{github.event.repository.name}}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: check docker images
        run: docker images

      - name: push image to DockerHub
        run: |
          docker tag ${{ github.event.repository.name }}:stable-${{ github.sha }} lakesyde/${{ github.event.repository.name }}:stable-${{ github.sha }}
          docker tag ${{ github.event.repository.name }}:latest lakesyde/${{ github.event.repository.name }}:latest
          docker push lakesyde/${{ github.event.repository.name }}
