name: aws-bootstrap

on: push

jobs:
  Test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ github.event.repository.name }}-${{ GITHUB_SHA }}
          restore-keys: |
            ${{ runner.os }}-${{ github.event.repository.name }}-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: lakesyde
          password: lakesyde03

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          outputs: type=docker
          tags: ola/aws-bootstrap:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: check docker images
        run: docker images
      # - name: Docker Buildx (build)
      #   run: |
      #     docker buildx build \
      #       --cache-from type=local,src=/tmp/.buildx-cache \
      #       --cache-to type=local,dest=/tmp/.buildx-cache \
      #       --load \
      #       --platform ${{ steps.prepare.outputs.docker_platforms }} \
      #       --tag "${{ steps.prepare.outputs.docker_image }}:${{ steps.prepare.outputs.hash }}" \
      #       --tag "${{ steps.prepare.outputs.repository }}-${{ github.event.client_payload.tags }}:latest" \
      #       --file Dockerfile .
